name: finance_app
description: "My Finance App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  cloud_firestore: ^5.6.9
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  dio: ^5.4.3
  equatable: ^2.0.7
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  firebase_storage: ^12.0.0
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  google_sign_in: ^6.3.0
  image_picker: ^1.0.7
  intl: ^0.20.2
  lottie: ^3.3.1
  permission_handler: ^11.3.1
  rxdart: ^0.28.0
  google_mlkit_text_recognition: ^0.13.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  go_router: ^14.6.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.4.11
  freezed: ^2.5.7
  json_serializable: ^6.8.0
flutter:
  uses-material-design: true
  assets:
    - assets/
